---
# tasks file for dispatcher-setup
 
- hosts: slave
  become: yes
  
  tasks:
    
  - name: Create folder
    file: 
      path: /opt/dispatcher-conf
      state: directory
      owner: root
      group: root
      mode: 0755
 
  - name: Download dispatcher tar file
    get_url:
      url: https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.2.3.tar.gz
      dest: /opt/dispatcher-conf
      mode: 0655
 
  - name: Unarchive tar file
    unarchive: 
      src: /opt/dispatcher-conf/dispatcher-apache2.4-linux-x86-64-4.2.3.tar.gz
      dest: /opt/dispatcher-conf
      owner: root
      remote_src: yes
  - name: stat dispatcher.so file
    stat: 
      path: /opt/dispatcher-conf/dispatcher-apache2.4-4.2.3.so
    register: foo_stat
  
  - name: Move dispatcher.so file inside /etc/httpd/modules
    command: "mv /opt/dispatcher-conf/dispatcher-apache2.4-4.2.3.so /etc/httpd/modules"
    when: foo_stat.stat.exists
    
    
  - name: Create symlink 
    file: 
      src: /etc/httpd/modules/dispatcher-apache2.4-4.2.3.so 
      dest: /etc/httpd/modules/mod_dispatcher.so
      state: link
 
  - name: Move dispatcher.any file inside /etc/httpd/conf
    command: "mv /opt/dispatcher-conf/conf/dispatcher.any /etc/httpd/conf/"
      
  - name: Change render ip inside dispatcher.any file.
    lineinfile:
       path: /etc/httpd/conf/dispatcher.any
       regexp: '/hostname "127.0.0.1"'
       line: '/hostname "192.168.56.102"'
       state: present
       backup: yes
 
  - name: Change port inside dispatcher.any file.
    lineinfile:
       path: /etc/httpd/conf/dispatcher.any
       regexp: '/port "8080"'
       line: '/port "4503"'
       state: present
       backup: yes
 
  - name: create virtual host conf file inside /etc/httpd/conf.d
    file: 
      path: /etc/httpd/conf.d/dispatcher-vhost.conf
      state: touch
      owner: root
      group: root
      mode: 0755
    
  - name: Create rewrite.conf file
    file:
      path: /etc/httpd/conf.d/rewrite.conf
      state: touch
      owner: root
      group: root
      mode: 0755 
  - name: Place rewrite default conf inside rewrite.conf file
    blockinfile:
      path: /etc/httpd/conf.d/rewrite.conf
      block: |
        RewriteEngine  on
 
  - name: Restart apache
    service: 
      name: httpd
      state: restarted
  
  - name: Run iptables 
    command: "iptables -F"
